# Generated by Django 5.0.3 on 2024-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options_alter_todolist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='public'),
        ),
    ]
